version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo